[project]
name = "fingerprint-diff"
version = "1.0.0"
description = "Tool to generate comparison images for Chromaprint fingerprints"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.3",
    "numpy>=2.3.0",
    "pyqt6>=6.9.1",
]
